import * as LucideIcons from "lucide-react";

// Fix: Use `typeof LucideIcons.Home` to infer the correct type
export const iconMap: Record<string, typeof LucideIcons.Home> = {
  Housing: LucideIcons.Home,
  Utilities: LucideIcons.Lightbulb,
  Groceries: LucideIcons.Utensils,
  Transportation: LucideIcons.Bus,
  Insurance: LucideIcons.Shield,
  Fund: LucideIcons.PiggyBank,
  Savings: LucideIcons.DollarSign,
  Investments: LucideIcons.Briefcase,
  Education: LucideIcons.Book,
  Payments: LucideIcons.PiggyBank,
  Loans: LucideIcons.Book,
  Mortgage: LucideIcons.Home,
  Dining: LucideIcons.Utensils,
  Entertainment: LucideIcons.Film,
  Hobbies: LucideIcons.Gamepad2,
  Gaming: LucideIcons.Gamepad2,
  Gym: LucideIcons.Dumbbell,
  Medical: LucideIcons.Hospital,
  Childcare: LucideIcons.Baby,
  Fees: LucideIcons.School,
  Travel: LucideIcons.Plane,
  Flight: LucideIcons.Plane,
  Donations: LucideIcons.HandHeart,
  Gifts: LucideIcons.Gift,
  Business: LucideIcons.Briefcase,
  Freelancing: LucideIcons.Laptop,
  Advertising: LucideIcons.Globe,
  Software: LucideIcons.Laptop,
  Pets: LucideIcons.PawPrint,
  Repairs: LucideIcons.Wrench,
  Shopping: LucideIcons.ShoppingBag,
  Subscriptions: LucideIcons.Ticket,
};
